spring:
  application:
    name: minio-spring
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
minio:
  access-key: admin
  secret-key: admin123456
  url: http://192.168.2.114:9000
server:
  port: 8080

